import { describe, expect, it, vi } from 'vitest';

import { runReleasePrAction } from '../../src/engine/release-pr-action.js';

describe('engine/release-pr-action — bot-owned release PR upsert (Task 9)', () => {
  const config = { branch: 'release/pending', base: 'main', appLogin: 'release-app[bot]' };
  const generatedFiles = { 'CHANGELOG.md': '# Changelog\n', VERSION: '1.2.4\n' };

  it('creates the generated branch and one App-authored release PR when none is open', async () => {
    const git = {
      readBranchFiles: vi.fn(async () => undefined),
      pushGeneratedBranch: vi.fn(async () => undefined),
    };
    const github = {
      findOpenReleasePullRequest: vi.fn(async () => undefined),
      createPullRequest: vi.fn(async () => ({ number: 42 })),
      updatePullRequest: vi.fn(async () => undefined),
    };

    await expect(runReleasePrAction({ git, github, config, generatedFiles, title: 'Release 1.2.4', body: 'Generated by release-app[bot].' }))
      .resolves.toEqual({ action: 'created', pullRequestNumber: 42, branchUpdated: true });

    expect(git.pushGeneratedBranch).toHaveBeenCalledWith({
      branch: 'release/pending',
      base: 'main',
      files: generatedFiles,
      message: 'chore(release): prepare 1.2.4',
    });
    expect(github.createPullRequest).toHaveBeenCalledWith({
      head: 'release/pending',
      base: 'main',
      title: 'Release 1.2.4',
      body: 'Generated by release-app[bot].',
    });
    expect(github.updatePullRequest).not.toHaveBeenCalled();
  });

  it('updates the one existing release PR and avoids a commit when generated surfaces are unchanged', async () => {
    const git = {
      readBranchFiles: vi.fn(async () => ({ ...generatedFiles })),
      pushGeneratedBranch: vi.fn(async () => undefined),
    };
    const github = {
      findOpenReleasePullRequest: vi.fn(async () => ({
        number: 42,
        author: config.appLogin,
        head: config.branch,
        base: config.base,
      })),
      createPullRequest: vi.fn(async () => ({ number: 99 })),
      updatePullRequest: vi.fn(async () => undefined),
    };

    await expect(runReleasePrAction({ git, github, config, generatedFiles, title: 'Release 1.2.4', body: 'Updated release description.' }))
      .resolves.toEqual({ action: 'updated', pullRequestNumber: 42, branchUpdated: false });

    expect(git.pushGeneratedBranch).not.toHaveBeenCalled();
    expect(github.updatePullRequest).toHaveBeenCalledWith({
      number: 42,
      title: 'Release 1.2.4',
      body: 'Updated release description.',
    });
    expect(github.createPullRequest).not.toHaveBeenCalled();
  });
});

describe('engine/release-pr-action — ownership and recovery (Task 10)', () => {
  const config = { branch: 'release/pending', base: 'main', appLogin: 'release-app[bot]' };
  const generatedFiles = { 'CHANGELOG.md': '# Changelog\n', VERSION: '1.2.4\n' };

  function ownedPullRequest(number = 42) {
    return { number, author: config.appLogin, base: config.base, head: config.branch };
  }

  function dependencies(overrides: {
    branchFiles?: Record<string, string>;
    pullRequest?: ReturnType<typeof ownedPullRequest> | undefined;
    create?: () => Promise<{ number: number }>;
  } = {}) {
    return {
      git: {
        readBranchFiles: vi.fn(async () => overrides.branchFiles),
        pushGeneratedBranch: vi.fn(async () => undefined),
      },
      github: {
        findOpenReleasePullRequest: vi.fn(async () => overrides.pullRequest),
        createPullRequest: vi.fn(overrides.create ?? (async () => ({ number: 42 }))),
        updatePullRequest: vi.fn(async () => undefined),
      },
    };
  }

  it('fails before GitHub or Git mutation when the configured App identity is absent', async () => {
    const { git, github } = dependencies();

    await expect(runReleasePrAction({
      git,
      github,
      config: { ...config, appLogin: '  ' },
      generatedFiles,
      title: 'Release 1.2.4',
      body: 'Generated release.',
    })).rejects.toThrow(/App identity/i);

    expect(git.readBranchFiles).not.toHaveBeenCalled();
    expect(github.findOpenReleasePullRequest).not.toHaveBeenCalled();
  });

  it.each([
    [{ ...ownedPullRequest(), author: 'foreign[bot]' }, 'owner'],
    [{ ...ownedPullRequest(), base: 'release-base' }, 'base'],
    [{ ...ownedPullRequest(), head: 'release/foreign' }, 'head'],
  ])('rejects a release PR with the wrong %s before mutating the generated branch', async (pullRequest, field) => {
    const { git, github } = dependencies({ pullRequest });

    await expect(runReleasePrAction({ git, github, config, generatedFiles, title: 'Release 1.2.4', body: 'Generated release.' }))
      .rejects.toThrow(new RegExp(field, 'i'));

    expect(git.pushGeneratedBranch).not.toHaveBeenCalled();
    expect(github.updatePullRequest).not.toHaveBeenCalled();
  });

  it('refuses to overwrite a foreign branch file outside the generated release surfaces', async () => {
    const { git, github } = dependencies({
      branchFiles: { ...generatedFiles, 'docs/foreign-edit.md': 'do not replace\n' },
      pullRequest: ownedPullRequest(),
    });

    await expect(runReleasePrAction({ git, github, config, generatedFiles, title: 'Release 1.2.4', body: 'Generated release.' }))
      .rejects.toThrow(/foreign.*docs\/foreign-edit\.md/i);

    expect(git.pushGeneratedBranch).not.toHaveBeenCalled();
    expect(github.updatePullRequest).not.toHaveBeenCalled();
  });

  it('recovers after a branch-only partial success without another push or a duplicate PR', async () => {
    const branchFiles: Record<string, string> = {};
    const git = {
      readBranchFiles: vi.fn(async () => Object.keys(branchFiles).length === 0 ? undefined : { ...branchFiles }),
      pushGeneratedBranch: vi.fn(async ({ files }: { files: Record<string, string> }) => {
        Object.assign(branchFiles, files);
      }),
    };
    let openPullRequest: ReturnType<typeof ownedPullRequest> | undefined;
    const github = {
      findOpenReleasePullRequest: vi.fn(async () => openPullRequest),
      createPullRequest: vi.fn(async () => {
        openPullRequest = ownedPullRequest(42);
        throw new Error('response lost after PR creation');
      }),
      updatePullRequest: vi.fn(async () => undefined),
    };
    const action = { git, github, config, generatedFiles, title: 'Release 1.2.4', body: 'Generated release.' };

    await expect(runReleasePrAction(action)).rejects.toThrow(/response lost/i);
    await expect(runReleasePrAction(action)).resolves.toEqual({ action: 'updated', pullRequestNumber: 42, branchUpdated: false });

    expect(git.pushGeneratedBranch).toHaveBeenCalledTimes(1);
    expect(github.createPullRequest).toHaveBeenCalledTimes(1);
    expect(github.updatePullRequest).toHaveBeenCalledTimes(1);
  });
});
