import { describe, expect, it, vi } from 'vitest';

import { runReleasePrAction } from '../../src/engine/release-pr-action.js';

describe('engine/release-pr-action — bot-owned release PR upsert (Task 9)', () => {
  const config = { branch: 'release/pending', base: 'main', appLogin: 'release-app[bot]' };
  const generatedFiles = { 'CHANGELOG.md': '# Changelog\n', VERSION: '1.2.4\n' };

  it('creates the generated branch and one App-authored release PR when none is open', async () => {
    const git = {
      readBranchFiles: vi.fn(async () => undefined),
      pushGeneratedBranch: vi.fn(async () => undefined),
    };
    const github = {
      findOpenReleasePullRequest: vi.fn(async () => undefined),
      createPullRequest: vi.fn(async () => ({ number: 42 })),
      updatePullRequest: vi.fn(async () => undefined),
    };

    await expect(runReleasePrAction({ git, github, config, generatedFiles, title: 'Release 1.2.4', body: 'Generated by release-app[bot].' }))
      .resolves.toEqual({ action: 'created', pullRequestNumber: 42, branchUpdated: true });

    expect(git.pushGeneratedBranch).toHaveBeenCalledWith({
      branch: 'release/pending',
      base: 'main',
      files: generatedFiles,
      message: 'chore(release): prepare 1.2.4',
    });
    expect(github.createPullRequest).toHaveBeenCalledWith({
      head: 'release/pending',
      base: 'main',
      title: 'Release 1.2.4',
      body: 'Generated by release-app[bot].',
    });
    expect(github.updatePullRequest).not.toHaveBeenCalled();
  });

  it('updates the one existing release PR and avoids a commit when generated surfaces are unchanged', async () => {
    const git = {
      readBranchFiles: vi.fn(async () => ({ ...generatedFiles })),
      pushGeneratedBranch: vi.fn(async () => undefined),
    };
    const github = {
      findOpenReleasePullRequest: vi.fn(async () => ({ number: 42 })),
      createPullRequest: vi.fn(async () => ({ number: 99 })),
      updatePullRequest: vi.fn(async () => undefined),
    };

    await expect(runReleasePrAction({ git, github, config, generatedFiles, title: 'Release 1.2.4', body: 'Updated release description.' }))
      .resolves.toEqual({ action: 'updated', pullRequestNumber: 42, branchUpdated: false });

    expect(git.pushGeneratedBranch).not.toHaveBeenCalled();
    expect(github.updatePullRequest).toHaveBeenCalledWith({
      number: 42,
      title: 'Release 1.2.4',
      body: 'Updated release description.',
    });
    expect(github.createPullRequest).not.toHaveBeenCalled();
  });
});
