import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { mkdtemp, rm, mkdir, writeFile, readFile } from 'fs/promises';
import { join } from 'path';
import { tmpdir } from 'os';
import { execFile as execFileCb } from 'child_process';
import { promisify } from 'util';
import { vi } from 'vitest';
import { discoverBacklog } from '../../src/engine/daemon-backlog.js';

// ─────────────────────────────────────────────────────────────────────────────
// RED acceptance specs for the Phase 9.3 REDESIGN authoring path (FR-6, the core
// fix; ADR-008; condition C2).
//
// The shipped (superseded) bug: authoring emitted a STUB stories file
// (`# Stories: <idea>\n\n_Generated by engineer._`) left at `Status: DRAFT`, via a
// spawned `claude -p` subprocess — so the daemon could never build it and the
// human gate was bypassed. The redesign replaces this with an AGENT-HOSTED
// DECIDE seam whose TypeScript primitive is deterministic: it commits the REAL
// human-gated artifacts onto a `spec/<slug>` branch, NEVER spawns `claude`, and
// the result passes the daemon's build-ready predicate (Status: Accepted +
// plan dependency tree).
//
// The new authoring seam (`runAuthoring`) does not exist yet, so it is
// dynamically imported INSIDE each test → per-test RED on the missing export.
//
// Contract the implementation must satisfy (defined by these specs):
//   runAuthoring(target, idea, deps): Promise<{ branch, project }>
//     deps.decide  : async (step, ctx) => { approved: boolean; artifact: string }
//                    // host-agent DECIDE seam; returns the human-gated artifact
//                    // for each of: 'brainstorm' | 'stories' | 'plan'.
//     deps.spawn?  : injected spawn (repo convention) — MUST stay uncalled for
//                    authoring (the superseded `claude -p` author run is gone).
//   On any UNAPPROVED step → throws/blocks, fabricates NO downstream artifact.
// ─────────────────────────────────────────────────────────────────────────────

const execFile = promisify(execFileCb);
const AUTHORING_MOD = '../../src/engine/engineer/authoring.js';

async function load(modPath: string): Promise<Record<string, unknown>> {
  return (await import(modPath)) as Record<string, unknown>;
}

function requireFn(mod: Record<string, unknown>, name: string): (...args: any[]) => any {
  const fn = mod[name];
  if (typeof fn !== 'function') {
    throw new Error(`expected export "${name}" to be a function (not yet implemented)`);
  }
  return fn as (...args: any[]) => any;
}

const STUB_STORIES = '# Stories: $IDEA\n\n_Generated by engineer._';

// Real, human-gated artifacts the host agent's DECIDE step would produce.
const ACCEPTED_STORIES = [
  '# Stories: CSV export',
  '',
  '**Status:** Accepted',
  '',
  '## Story: Export rows to CSV',
  '',
  '### Acceptance Criteria',
  '- Given rows, when I export, then a CSV is produced.',
  '',
].join('\n');

const PLAN_WITH_DEPS = [
  '# Implementation Plan: CSV export',
  '',
  '**Stories:** .docs/stories/csv-export.md',
  '',
  '## Tasks',
  '',
  '### Task 1: writer',
  '**Dependencies:** none',
  '',
  '## Task Dependency Graph',
  '```',
  '1 → 2',
  '```',
  '',
].join('\n');

let repoPath: string;
let defaultBranch: string;

async function git(args: string[], cwd: string): Promise<string> {
  const { stdout } = await execFile('git', args, { cwd });
  return stdout.trim();
}

beforeEach(async () => {
  repoPath = await mkdtemp(join(tmpdir(), 'engineer-authoring-'));
  await execFile('git', ['init', '-q'], { cwd: repoPath });
  await execFile('git', ['config', 'user.email', 'test@test.com'], { cwd: repoPath });
  await execFile('git', ['config', 'user.name', 'Test'], { cwd: repoPath });
  await writeFile(join(repoPath, 'README.md'), '# repo\n');
  await execFile('git', ['add', 'README.md'], { cwd: repoPath });
  await execFile('git', ['commit', '-m', 'init'], { cwd: repoPath });
  defaultBranch = await git(['rev-parse', '--abbrev-ref', 'HEAD'], repoPath);
});

afterEach(async () => {
  vi.restoreAllMocks();
  await rm(repoPath, { recursive: true, force: true });
});

function makeTarget() {
  return { name: 'alpha', canonicalPath: repoPath };
}

/** A DECIDE seam that returns the real human-gated, APPROVED artifacts. */
function approvedDecide() {
  return async (step: string) => {
    if (step === 'brainstorm') return { approved: true, artifact: '# PRD: CSV export\n\nApproved.\n' };
    if (step === 'stories') return { approved: true, artifact: ACCEPTED_STORIES };
    if (step === 'plan') return { approved: true, artifact: PLAN_WITH_DEPS };
    return { approved: true, artifact: '' };
  };
}

// ═════════════════════════════════════════════════════════════════════════════
// FR-6 / C2 (the core fix): authoring produces REAL accepted artifacts that the
// daemon's build-ready predicate accepts — and never the stub, never DRAFT,
// never via a claude subprocess.
// ═════════════════════════════════════════════════════════════════════════════
describe('engineer authoring → real accepted artifacts (FR-6, C2)', () => {
  it('commits Accepted stories + dependency-tree plan on spec/<slug>; build-ready only after MERGE (FR-24)', async () => {
    const runAuthoring = requireFn(await load(AUTHORING_MOD), 'runAuthoring');

    const result = await runAuthoring(makeTarget(), 'CSV export', { decide: approvedDecide() });

    // A spec/<slug> branch was created.
    const branches = await git(['branch', '--list', 'spec/*'], repoPath);
    expect(branches).toMatch(/spec\//);
    expect(result.branch).toMatch(/^spec\//);

    // FR-24: on the spec branch (unmerged), the daemon's predicate finds nothing
    // — the operator's merge is the build-ready signal, not authoring alone.
    const before = await discoverBacklog(repoPath, undefined, undefined, {
      baseBranch: defaultBranch,
    });
    expect(before).toEqual([]);

    // Merge the spec branch into the base branch (the operator's action).
    await execFile('git', ['checkout', defaultBranch], { cwd: repoPath });
    await execFile('git', ['merge', '--no-ff', '-m', 'merge spec', result.branch], {
      cwd: repoPath,
    });

    // Now the predicate the DAEMON uses passes (Status:Accepted + dependency tree).
    const after = await discoverBacklog(repoPath, undefined, undefined, {
      baseBranch: defaultBranch,
    });
    expect(after.length).toBeGreaterThan(0);
  });

  it('produced stories are NEVER the stub string and NEVER Status: DRAFT', async () => {
    const runAuthoring = requireFn(await load(AUTHORING_MOD), 'runAuthoring');

    const result = await runAuthoring(makeTarget(), 'CSV export', { decide: approvedDecide() });
    await execFile('git', ['checkout', result.branch], { cwd: repoPath });

    // Locate the committed stories file and inspect it.
    // `git show branch:.docs/stories` returns a tree listing like:
    //   tree spec/slug:.docs/stories
    //
    //   csv-export.md
    //
    // Filter out the header line (starts with "tree ") and blank lines to get filenames.
    const storiesTreeOutput = await git(
      ['show', `${result.branch}:.docs/stories`],
      repoPath,
    ).catch(async () =>
      // fallback: ls the working tree
      (await execFile('ls', [join(repoPath, '.docs', 'stories')])).stdout.trim(),
    );
    expect(storiesTreeOutput.length).toBeGreaterThan(0);

    const storiesFile = storiesTreeOutput
      .split('\n')
      .map((s) => s.trim())
      .filter((s) => s.length > 0 && !s.startsWith('tree '))[0];
    const storiesText = await readFile(join(repoPath, '.docs', 'stories', storiesFile), 'utf8');

    // Regression guard on the exact shipped bug.
    expect(storiesText).not.toContain('_Generated by engineer._');
    expect(storiesText.trim()).not.toBe(STUB_STORIES.replace('$IDEA', 'CSV export').trim());
    expect(storiesText).not.toMatch(/\bstatus\b[\s*:]*\bdraft\b/i);
    expect(storiesText).toMatch(/\bstatus\b[\s*:]*\baccepted\b/i);
  });

  it('spawns ZERO claude/claude -p subprocesses during authoring (injected spawn spy)', async () => {
    // Repo convention (see daemon-launch.test.ts): inject the spawn fn rather
    // than mutate the ESM child_process namespace. The authoring seam must never
    // spawn a `claude` author subprocess — ideally never spawn at all.
    const spawnSpy = vi.fn().mockReturnValue({ pid: 1, unref: () => {} });
    const runAuthoring = requireFn(await load(AUTHORING_MOD), 'runAuthoring');

    await runAuthoring(makeTarget(), 'CSV export', {
      decide: approvedDecide(),
      spawn: spawnSpy,
    });

    // No spawned process may be `claude` (the superseded `claude -p` author run).
    for (const call of spawnSpy.mock.calls) {
      const cmd = String(call[0] ?? '');
      const args = (call[1] as unknown[] | undefined)?.map(String) ?? [];
      expect(cmd).not.toMatch(/(^|\/)claude$/);
      expect([cmd, ...args].join(' ')).not.toMatch(/\bclaude\b\s+-p\b/);
    }
  });

  it('an UNAPPROVED DECIDE gate blocks — no downstream artifact is fabricated', async () => {
    const runAuthoring = requireFn(await load(AUTHORING_MOD), 'runAuthoring');

    // The operator does NOT approve the stories step → authoring must block.
    const blockingDecide = async (step: string) => {
      if (step === 'brainstorm') return { approved: true, artifact: '# PRD\n' };
      if (step === 'stories') return { approved: false, artifact: '' };
      // plan must never be reached.
      return { approved: true, artifact: PLAN_WITH_DEPS };
    };

    await expect(
      runAuthoring(makeTarget(), 'CSV export', { decide: blockingDecide }),
    ).rejects.toThrow();

    // The plan artifact must NOT have been written/committed (no fabrication
    // past the unapproved gate). The repo is back on its default branch with no
    // committed plan on any spec branch for this idea.
    await execFile('git', ['checkout', defaultBranch], { cwd: repoPath }).catch(() => undefined);
    const planFiles = await execFile('ls', [join(repoPath, '.docs', 'plans')])
      .then((r) => r.stdout.trim())
      .catch(() => '');
    expect(planFiles).toBe('');
  });
});
