/**
 * Git hook scripts embedded as engine assets
 *
 * Both hooks are written to .pipeline/git-hooks/ at worktree provisioning
 * and wired via git config core.hooksPath. They use only bash, git, node -e,
 * and POSIX tools — no dist references, no conduct-ts invocations.
 */

/**
 * prepare-commit-msg hook
 * Stamps/reconciles Task: <id> via git interpret-trailers. The engine's
 * .pipeline/current-task id always wins over any self-stamped Task: trailer
 * already present in the message (replaces, never appends a duplicate).
 * ID comes from .pipeline/current-task, else abstains (message untouched).
 * Abstains on amend, rebase-in-progress, or when current-task is absent.
 */
export const PREPARE_COMMIT_MSG_HOOK = [
  '#!/bin/bash',
  'set -e',
  '',
  'COMMIT_MSG_FILE="$1"',
  'COMMIT_SOURCE="${2:-}"',
  '',
  '# Abstain during amend (never restamp old commits)',
  'if [[ "$COMMIT_SOURCE" == "commit" ]]; then',
  '  exit 0',
  'fi',
  '',
  '# Abstain during rebase (replayed commits are never restamped)',
  'if [[ -d "$(git rev-parse --git-path rebase-merge)" ]] || [[ -d "$(git rev-parse --git-path rebase-apply)" ]]; then',
  '  exit 0',
  'fi',
  '',
  '# Abstain if there are no staged changes (amend with just message change)',
  '# This prevents adding a Task: trailer to empty commits',
  'if git diff-index --cached --quiet HEAD 2>/dev/null; then',
  '  exit 0',
  'fi',
  '',
  'WORKTREE_ROOT="$(git rev-parse --show-toplevel)"',
  'CURRENT_TASK_FILE="$WORKTREE_ROOT/.pipeline/current-task"',
  'TASK_STATUS_FILE="$WORKTREE_ROOT/.pipeline/task-status.json"',
  '',
  '# Try to get task id from current-task file',
  'TASK_ID=""',
  'if [[ -f "$CURRENT_TASK_FILE" ]]; then',
  '  TASK_ID="$(cat "$CURRENT_TASK_FILE" 2>/dev/null || true)"',
  'fi',
  '',
  '# If we have a task id, stamp/reconcile the trailer — the engine\'s',
  '# current-task id always wins over any self-stamped Task: trailer already',
  '# present in the message (--if-exists replace ensures replace, not append).',
  'if [[ -n "$TASK_ID" ]]; then',
  '  git interpret-trailers --in-place --if-exists replace --trailer "Task: $TASK_ID" "$COMMIT_MSG_FILE" || true',
  'fi',
  '',
  '# Chain to the repository\'s own prepare-commit-msg hook if it exists',
  'COMMON_DIR="$(git rev-parse --git-common-dir)"',
  'COMMON_HOOKS_DIR="$COMMON_DIR/hooks"',
  'if [[ ! "$COMMON_DIR" = /* ]]; then',
  '  # Relative path — make it absolute',
  '  COMMON_HOOKS_DIR="$(git rev-parse --show-toplevel)/$COMMON_DIR/hooks"',
  'fi',
  'CHAINED_HOOK="$COMMON_HOOKS_DIR/prepare-commit-msg"',
  '',
  'if [[ -x "$CHAINED_HOOK" ]]; then',
  '  "$CHAINED_HOOK" "$@" || exit $?',
  'fi',
  '',
  'exit 0',
].join('\n');

/**
 * commit-msg hook
 *
 * Task 14 (#773): per-task commit attribution/evidence is demoted from a
 * gate to telemetry. This hook no longer rejects commits for missing or
 * unresolvable Task:/Evidence: trailers — that fail-closed behavior
 * (formerly "Surface A", #505 Task 5/7) is retired.
 *
 * What remains: when a Task: trailer IS present, its FORMAT is still
 * validated (rejects task-N naming drift; rejects an id not present in
 * task-status.json). Warns (never blocks) on bundling and
 * subject-vs-trailer mismatch. Chains to $GIT_COMMON_DIR/hooks/commit-msg
 * if it exists.
 */
export const COMMIT_MSG_HOOK = [
  '#!/bin/bash',
  'set -e',
  '',
  'COMMIT_MSG_FILE="$1"',
  '',
  'WORKTREE_ROOT="$(git rev-parse --show-toplevel)"',
  'TASK_STATUS_FILE="$WORKTREE_ROOT/.pipeline/task-status.json"',
  '',
  '# Extract Task: trailer value',
  'TASK_TRAILER=$(git interpret-trailers --parse < "$COMMIT_MSG_FILE" 2>/dev/null | grep \'^Task:\' | head -1 | sed \'s/^Task: *//\' || true)',
  '',
  '# Extract Evidence: satisfied-by value',
  'EVIDENCE_TRAILER=$(git interpret-trailers --parse < "$COMMIT_MSG_FILE" 2>/dev/null | grep \'^Evidence: satisfied-by\' | head -1 | sed \'s/^Evidence: satisfied-by *//\' || true)',
  '',
  '# Extract Evidence: skipped <reason> value (alternative acceptance form for',
  '# empty commits — mirrors the deriver in autoheal.ts, which already treats',
  '# this trailer as satisfying a task).',
  'EVIDENCE_SKIPPED_REASON=$(git interpret-trailers --parse < "$COMMIT_MSG_FILE" 2>/dev/null | grep \'^Evidence: skipped\' | head -1 | sed \'s/^Evidence: skipped *//\' | sed \'s/^[[:space:]]*//;s/[[:space:]]*$//\' || true)',
  '',
  '# Surface A (#505 Task 5): fail-closed rejection of unattributed content',
  '# commits made during an active build-step session. The',
  '# .pipeline/build-step-active marker is written by the engine around a',
  '# dispatched build step (removed in a finally); its presence already',
  '# encodes "build step running AND attribution enforcement cutover passed" —',
  '# this hook only checks for the file, it never parses config or YAML.',
  '',
  '# Exemption: merge commits legitimately lack a Task: trailer — MERGE_HEAD',
  '# is set by git itself for the duration of a merge commit.',
  'MERGE_HEAD_PATH="$(git rev-parse --git-path MERGE_HEAD 2>/dev/null || true)"',
  'if [[ -n "$MERGE_HEAD_PATH" ]] && [[ -f "$MERGE_HEAD_PATH" ]]; then',
  '  exit 0',
  'fi',
  '',
  '# Exemption: amend of a pre-enforcement commit. GIT_REFLOG_ACTION is not',
  '# reliably set in this hook\'s environment across git versions or when -m is',
  '# combined with --amend, so fall back to inspecting the invoking git',
  '# process\'s own command line (our direct parent, always `git commit ...`)',
  '# for the --amend flag; the amended commit predates enforcement by',
  '# definition (it already exists).',
  'if [[ "${GIT_REFLOG_ACTION:-}" == "commit (amend)" ]]; then',
  '  exit 0',
  'fi',
  'PARENT_GIT_CMD="$(ps -o args= -p "$PPID" 2>/dev/null || true)"',
  'if [[ "$PARENT_GIT_CMD" == *"commit"*"--amend"* ]]; then',
  '  exit 0',
  'fi',
  '',
  '# Exemption: commits replayed during a rebase are never restamped.',
  'REBASE_MERGE_PATH="$(git rev-parse --git-path rebase-merge 2>/dev/null || true)"',
  'REBASE_APPLY_PATH="$(git rev-parse --git-path rebase-apply 2>/dev/null || true)"',
  'if { [[ -n "$REBASE_MERGE_PATH" ]] && [[ -d "$REBASE_MERGE_PATH" ]]; } || { [[ -n "$REBASE_APPLY_PATH" ]] && [[ -d "$REBASE_APPLY_PATH" ]]; }; then',
  '  exit 0',
  'fi',
  '',
  '# Exemption (#505 Task 7): engine-authored bookkeeping commits. The engine',
  '# sets CONDUCT_ENGINE_COMMIT=1 in the environment for the duration of a',
  '# commit it makes itself (not a dispatched agent); these are never subject',
  '# to attribution enforcement.',
  'if [[ "${CONDUCT_ENGINE_COMMIT:-}" == "1" ]]; then',
  '  exit 0',
  'fi',
  '',
  '# Task 14 (#773): commit evidence rejection is retired — per-task',
  '# attribution/evidence is now telemetry, not a gate. Missing Task:/',
  '# Evidence: trailers on a build-step commit no longer block the commit.',
  '',
  '# If there\'s a Task: trailer, validate its FORMAT (this is not gating on',
  '# presence — it only fires when a trailer was actually supplied).',
  'if [[ -n "$TASK_TRAILER" ]]; then',
  '  # Reject task-N format (naming drift)',
  '  if [[ "$TASK_TRAILER" =~ ^task- ]]; then',
  '    echo "commit-msg: rejected — Task: trailer uses task-N format; must be numeric id only" >&2',
  '    exit 1',
  '  fi',
  '',
  '  # Check if id exists in task-status.json',
  '  if [[ -f "$TASK_STATUS_FILE" ]]; then',
  '    ID_EXISTS=$(node -e "',
  '      const fs = require(\'fs\');',
  '      try {',
  '        const data = JSON.parse(fs.readFileSync(\'$TASK_STATUS_FILE\', \'utf-8\'));',
  '        const ids = (Array.isArray(data.tasks) ? data.tasks : []).map(t => String(t && t.id));',
  '        console.log(ids.includes(\'$TASK_TRAILER\') ? \'yes\' : \'no\');',
  '      } catch {',
  '        console.log(\'no\');',
  '      }',
  '    " 2>/dev/null || echo "no")',
  '',
  '    if [[ "$ID_EXISTS" != "yes" ]]; then',
  '      echo "commit-msg: rejected — Task: $TASK_TRAILER not found in task-status.json" >&2',
  '      exit 1',
  '    fi',
  '  fi',
  '',
  '  # Task 14 (#773): the empty-commit Evidence: requirement is retired —',
  '  # evidence trailers are telemetry now, not a gate. An empty build-step',
  '  # commit with a Task: trailer no longer needs an Evidence: trailer.',
  '',
  '  # Warn (don\'t block) on bundling check — best effort based on files mapping',
  '  if [[ -f "$TASK_STATUS_FILE" ]]; then',
  '    node -e "',
  '      const fs = require(\'fs\');',
  '      try {',
  '        const data = JSON.parse(fs.readFileSync(\'$TASK_STATUS_FILE\', \'utf-8\'));',
  '        const tasks = data.tasks || [];',
  '',
  '        // Get staged files',
  '        const { execSync } = require(\'child_process\');',
  '        let stagedFiles = [];',
  '        try {',
  '          const output = execSync(\'git diff-index --cached --name-only HEAD\', {',
  '            encoding: \'utf-8\',',
  '            stdio: [\'pipe\', \'pipe\', \'ignore\']',
  '          });',
  '          stagedFiles = output.trim().split(\'\\n\').filter(f => f);',
  '        } catch {}',
  '',
  '        if (stagedFiles.length > 0) {',
  '          const tasksByFile = {};',
  '          tasks.forEach(t => {',
  '            if (t.files && Array.isArray(t.files)) {',
  '              t.files.forEach(f => {',
  '                tasksByFile[f] = t.id;',
  '              });',
  '            }',
  '          });',
  '',
  '          const mappedTasks = new Set();',
  '          stagedFiles.forEach(f => {',
  '            if (tasksByFile[f]) {',
  '              mappedTasks.add(tasksByFile[f]);',
  '            }',
  '          });',
  '',
  '          if (mappedTasks.size > 1) {',
  '            console.error(\'commit-msg: WARNING — staged diff spans files of multiple plan tasks\');',
  '          }',
  '        }',
  '      } catch {}',
  '    " || true',
  '  fi',
  '',
  '  # Warn on subject vs trailer mismatch',
  '  SUBJECT=$(head -1 "$COMMIT_MSG_FILE" || true)',
  '  if [[ "$SUBJECT" =~ [Tt]ask[[:space:]]+[0-9] ]]; then',
  '    # Extract numeric task reference from subject (e.g., "Task 5" or "task 7")',
  '    SUBJECT_TASK=$(echo "$SUBJECT" | grep -oE \'[Tt]ask[[:space:]]+[0-9]+\' | grep -oE \'[0-9]+\' || true)',
  '    if [[ -n "$SUBJECT_TASK" ]] && [[ "$SUBJECT_TASK" != "$TASK_TRAILER" ]]; then',
  '      echo "commit-msg: WARNING — subject references Task $SUBJECT_TASK but trailer is Task: $TASK_TRAILER" >&2',
  '    fi',
  '  fi',
  'fi',
  '',
  '# Chain to the repository\'s own commit-msg hook if it exists',
  'COMMON_DIR="$(git rev-parse --git-common-dir)"',
  'COMMON_HOOKS_DIR="$COMMON_DIR/hooks"',
  'if [[ ! "$COMMON_DIR" = /* ]]; then',
  '  # Relative path — make it absolute',
  '  COMMON_HOOKS_DIR="$(git rev-parse --show-toplevel)/$COMMON_DIR/hooks"',
  'fi',
  'CHAINED_HOOK="$COMMON_HOOKS_DIR/commit-msg"',
  '',
  'if [[ -x "$CHAINED_HOOK" ]]; then',
  '  "$CHAINED_HOOK" "$COMMIT_MSG_FILE" "$@" || exit $?',
  'fi',
  '',
  'exit 0',
].join('\n');
