/**
 * Git hook scripts embedded as engine assets
 *
 * Both hooks are written to .pipeline/git-hooks/ at worktree provisioning
 * and wired via git config core.hooksPath. They use only bash, git, node -e,
 * and POSIX tools — no dist references, no conduct-ts invocations.
 */

/**
 * prepare-commit-msg hook
 * Appends Task: <id> via git interpret-trailers when no trailer exists.
 * ID comes from .pipeline/current-task, else the unique in_progress row.
 * Abstains on ambiguity, amend, rebase-in-progress, or corrupt JSON.
 */
export const PREPARE_COMMIT_MSG_HOOK = [
  '#!/bin/bash',
  'set -e',
  '',
  '# Fail gracefully on error — never block the commit',
  'cleanup() {',
  '  :',
  '}',
  'trap cleanup EXIT',
  '',
  'COMMIT_MSG_FILE="$1"',
  'COMMIT_SOURCE="${2:-}"',
  '',
  '# Abstain during amend (never restamp old commits)',
  'if [[ "$COMMIT_SOURCE" == "commit" ]]; then',
  '  exit 0',
  'fi',
  '',
  '# Abstain during rebase (replayed commits are never restamped)',
  'if [[ -d "$(git rev-parse --git-path rebase-merge)" ]] || [[ -d "$(git rev-parse --git-path rebase-apply)" ]]; then',
  '  exit 0',
  'fi',
  '',
  '# Check if a Task: trailer already exists',
  'if git interpret-trailers --in-place --parse < "$COMMIT_MSG_FILE" 2>/dev/null | grep -q \'^Task:\'; then',
  '  exit 0',
  'fi',
  '',
  'WORKTREE_ROOT="$(git rev-parse --show-toplevel)"',
  'CURRENT_TASK_FILE="$WORKTREE_ROOT/.pipeline/current-task"',
  'TASK_STATUS_FILE="$WORKTREE_ROOT/.pipeline/task-status.json"',
  '',
  '# Try to get task id from current-task file',
  'TASK_ID=""',
  'if [[ -f "$CURRENT_TASK_FILE" ]]; then',
  '  TASK_ID="$(cat "$CURRENT_TASK_FILE" 2>/dev/null || true)"',
  'fi',
  '',
  '# Fall back to unique in_progress row if current-task is absent',
  'if [[ -z "$TASK_ID" ]] && [[ -f "$TASK_STATUS_FILE" ]]; then',
  '  # Parse JSON safely via node — avoid jq dependency',
  '  TASK_ID=$(node -e "',
  '    const fs = require(\'fs\');',
  '    try {',
  '      const data = JSON.parse(fs.readFileSync(\'$TASK_STATUS_FILE\', \'utf-8\'));',
  '      const inProgress = (data.tasks || []).filter(t => t.status === \'in_progress\');',
  '      if (inProgress.length === 1) {',
  '        console.log(inProgress[0].id);',
  '      }',
  '    } catch {}',
  '  " 2>/dev/null || true)',
  'fi',
  '',
  '# If we have a task id, stamp the trailer',
  'if [[ -n "$TASK_ID" ]]; then',
  '  git interpret-trailers --in-place --trailer "Task: $TASK_ID" "$COMMIT_MSG_FILE" || true',
  'fi',
  '',
  'exit 0',
].join('\n');

/**
 * commit-msg hook
 * Validates Task: trailer id (must exist in task-status.json, never task-N format).
 * Rejects empty commits lacking a resolvable Evidence: satisfied-by <sha>.
 * Warns (never blocks) on bundling and subject-vs-trailer mismatch.
 * Chains to $GIT_COMMON_DIR/hooks/commit-msg if it exists.
 */
export const COMMIT_MSG_HOOK = [
  '#!/bin/bash',
  'set -e',
  '',
  'COMMIT_MSG_FILE="$1"',
  '',
  'WORKTREE_ROOT="$(git rev-parse --show-toplevel)"',
  'TASK_STATUS_FILE="$WORKTREE_ROOT/.pipeline/task-status.json"',
  '',
  '# Extract Task: trailer value',
  'TASK_TRAILER=$(git interpret-trailers --in-place --parse < "$COMMIT_MSG_FILE" 2>/dev/null | grep \'^Task:\' | head -1 | sed \'s/^Task: *//\' || true)',
  '',
  '# Extract Evidence: satisfied-by value',
  'EVIDENCE_TRAILER=$(git interpret-trailers --in-place --parse < "$COMMIT_MSG_FILE" 2>/dev/null | grep \'^Evidence: satisfied-by\' | head -1 | sed \'s/^Evidence: satisfied-by *//\' || true)',
  '',
  '# If there\'s a Task: trailer, validate it',
  'if [[ -n "$TASK_TRAILER" ]]; then',
  '  # Reject task-N format (naming drift)',
  '  if [[ "$TASK_TRAILER" =~ ^task- ]]; then',
  '    echo "commit-msg: rejected — Task: trailer uses task-N format; must be numeric id only" >&2',
  '    exit 1',
  '  fi',
  '',
  '  # Check if id exists in task-status.json',
  '  if [[ -f "$TASK_STATUS_FILE" ]]; then',
  '    ID_EXISTS=$(node -e "',
  '      const fs = require(\'fs\');',
  '      try {',
  '        const data = JSON.parse(fs.readFileSync(\'$TASK_STATUS_FILE\', \'utf-8\'));',
  '        const ids = (data.tasks || []).map(t => t.id);',
  '        console.log(ids.includes(\'$TASK_TRAILER\') ? \'yes\' : \'no\');',
  '      } catch {',
  '        console.log(\'no\');',
  '      }',
  '    " 2>/dev/null || echo "no")',
  '',
  '    if [[ "$ID_EXISTS" != "yes" ]]; then',
  '      echo "commit-msg: rejected — Task: $TASK_TRAILER not found in task-status.json" >&2',
  '      exit 1',
  '    fi',
  '  fi',
  '',
  '  # Check if this is an empty commit',
  '  IS_EMPTY=$(git diff-index --cached --quiet HEAD 2>/dev/null && echo "yes" || echo "no")',
  '  if [[ "$IS_EMPTY" == "yes" ]]; then',
  '    # Empty commit must have resolvable Evidence: satisfied-by',
  '    if [[ -z "$EVIDENCE_TRAILER" ]]; then',
  '      echo "commit-msg: rejected — empty commit requires Evidence: satisfied-by <sha>" >&2',
  '      exit 1',
  '    fi',
  '',
  '    # Verify the sha exists',
  '    if ! git cat-file -e "$EVIDENCE_TRAILER^{commit}" 2>/dev/null; then',
  '      echo "commit-msg: rejected — Evidence: satisfied-by $EVIDENCE_TRAILER not found in repository" >&2',
  '      exit 1',
  '    fi',
  '  fi',
  '',
  '  # Warn (don\'t block) on bundling check — best effort based on files mapping',
  '  if [[ -f "$TASK_STATUS_FILE" ]]; then',
  '    node -e "',
  '      const fs = require(\'fs\');',
  '      try {',
  '        const data = JSON.parse(fs.readFileSync(\'$TASK_STATUS_FILE\', \'utf-8\'));',
  '        const tasks = data.tasks || [];',
  '',
  '        // Get staged files',
  '        const { execSync } = require(\'child_process\');',
  '        let stagedFiles = [];',
  '        try {',
  '          const output = execSync(\'git diff-index --cached --name-only HEAD\', {',
  '            encoding: \'utf-8\',',
  '            stdio: [\'pipe\', \'pipe\', \'ignore\']',
  '          });',
  '          stagedFiles = output.trim().split(\'\\n\').filter(f => f);',
  '        } catch {}',
  '',
  '        if (stagedFiles.length > 0) {',
  '          const tasksByFile = {};',
  '          tasks.forEach(t => {',
  '            if (t.files && Array.isArray(t.files)) {',
  '              t.files.forEach(f => {',
  '                tasksByFile[f] = t.id;',
  '              });',
  '            }',
  '          });',
  '',
  '          const mappedTasks = new Set();',
  '          stagedFiles.forEach(f => {',
  '            if (tasksByFile[f]) {',
  '              mappedTasks.add(tasksByFile[f]);',
  '            }',
  '          });',
  '',
  '          if (mappedTasks.size > 1 && !mappedTasks.has(\'$TASK_TRAILER\')) {',
  '            console.error(\'commit-msg: WARNING — staged diff spans files of multiple plan tasks\');',
  '          }',
  '        }',
  '      } catch {}',
  '    " || true',
  '  fi',
  '',
  '  # Warn on subject vs trailer mismatch',
  '  SUBJECT=$(head -1 "$COMMIT_MSG_FILE" || true)',
  '  if [[ "$SUBJECT" =~ [Tt]ask[[:space:]]+[0-9] ]]; then',
  '    # Extract numeric task reference from subject (e.g., "Task 5" or "task 7")',
  '    SUBJECT_TASK=$(echo "$SUBJECT" | grep -oE \'[Tt]ask[[:space:]]+[0-9]+\' | grep -oE \'[0-9]+\' || true)',
  '    if [[ -n "$SUBJECT_TASK" ]] && [[ "$SUBJECT_TASK" != "$TASK_TRAILER" ]]; then',
  '      echo "commit-msg: WARNING — subject references Task $SUBJECT_TASK but trailer is Task: $TASK_TRAILER" >&2',
  '    fi',
  '  fi',
  'fi',
  '',
  '# Chain to the repository\'s own commit-msg hook if it exists',
  'COMMON_DIR="$(git rev-parse --git-common-dir)"',
  'COMMON_HOOKS_DIR="$COMMON_DIR/hooks"',
  'if [[ ! "$COMMON_DIR" = /* ]]; then',
  '  # Relative path — make it absolute',
  '  COMMON_HOOKS_DIR="$(git rev-parse --show-toplevel)/$COMMON_DIR/hooks"',
  'fi',
  'CHAINED_HOOK="$COMMON_HOOKS_DIR/commit-msg"',
  '',
  'if [[ -x "$CHAINED_HOOK" ]]; then',
  '  "$CHAINED_HOOK" "$COMMIT_MSG_FILE" "$@" || exit $?',
  'fi',
  '',
  'exit 0',
].join('\n');
