/**
 * Session-lifecycle hook scripts embedded as engine assets
 *
 * Both hooks are written to .pipeline/session-hooks/ at worktree provisioning
 * and wired via settings.json hook entries. They use only bash and POSIX
 * tools — no dist references, no conduct-ts invocations. stdin is bounded
 * via `head -c` so a runaway payload can never hang or OOM the hook.
 */

/**
 * PreToolUse-style dispatch hook (pre-dispatch)
 * Invoked before a subagent is dispatched. Reads the bounded hook payload
 * from stdin, extracts line 1 of `tool_input.prompt`, and passes through
 * (exit 0, no state touched) when it is exactly "Task: none". Further
 * behavior for real task ids is added in later tasks.
 */
export const PRE_DISPATCH_HOOK = [
  '#!/bin/bash',
  'set -e',
  '',
  '# Bound stdin read to 1MiB to avoid hanging or OOMing on a runaway payload',
  '# timeout 3: never hang the session if the host holds hook stdin open —',
  '# a timed-out (empty/partial) payload falls through the fail-open path.',
  'PAYLOAD="$(timeout 3 head -c 1048576 2>/dev/null || true)"',
  '',
  '# Extract line 1 of tool_input.prompt via a bounded node JSON parse. A',
  '# malformed/missing prompt yields an empty LINE1, which simply falls',
  '# through to the (currently no-op) tail of the hook.',
  'LINE1="$(printf \'%s\' "$PAYLOAD" | node -e \'',
  'let data = "";',
  'process.stdin.on("data", (chunk) => { data += chunk; });',
  'process.stdin.on("end", () => {',
  '  try {',
  '    const payload = JSON.parse(data);',
  '    const prompt = payload && payload.tool_input && payload.tool_input.prompt;',
  '    if (typeof prompt === "string") {',
  '      process.stdout.write(prompt.split("\\n")[0]);',
  '    }',
  '  } catch (err) {',
  '    // Malformed/unparseable payload — fail open: emit a diagnostic on',
  '    // stderr and nothing on stdout, so the caller falls through to the',
  '    // no-op tail (exit 0) rather than blocking the dispatch.',
  '    process.stderr.write(',
  '      "pre-dispatch-hook: unparseable payload, passing through: " + String(err && err.message) + "\\n"',
  '    );',
  '  }',
  '});',
  '\' || true)"',
  '',
  '# Fail-open: an empty LINE1 means the payload was unparseable or had no',
  '# tool_input.prompt at all (no signal to validate) — pass through quietly',
  '# rather than treating "nothing to say" as a grammar violation.',
  'if [ -z "$LINE1" ]; then',
  '  exit 0',
  'fi',
  '',
  '# Grammar enforcement: line 1 MUST be exactly "Task: <id>" or "Task: none".',
  '# Anything else — wrong case, missing space, multiple markers, trailing',
  '# prose — blocks the dispatch with exit 2 and an instructive error so the',
  '# caller can fix the prompt and retry.',
  'if ! [[ "$LINE1" =~ ^Task:\\ ([A-Za-z0-9._-]+|none)$ ]]; then',
  '  echo "PRE dispatch hook: line 1 of the prompt must be exactly \\"Task: <id>\\" or \\"Task: none\\"." >&2',
  '  echo "Got: ${LINE1}" >&2',
  '  echo "Example: \\"Task: 7\\" or \\"Task: none\\"" >&2',
  '  exit 2',
  'fi',
  '',
  '# Record a dispatch-count sentinel: every grammar-valid "Task: <id>" or',
  '# "Task: none" dispatch appends one line to .pipeline/dispatch-count,',
  '# regardless of subsequent branch outcome. Used by later zero-work',
  '# detection (Task 15) to tell whether any dispatch happened at all.',
  '# Idempotent/best-effort: created if absent, appended to otherwise; a',
  '# failure here (e.g. read-only fs) must never block the dispatch.',
  'mkdir -p .pipeline 2>/dev/null || true',
  'echo "$LINE1" >> .pipeline/dispatch-count 2>/dev/null || true',
  '',
  '# Task: none — pass through without touching any pipeline state.',
  'if [ "$LINE1" = "Task: none" ]; then',
  '  exit 0',
  'fi',
  '',
  '# Task: <id> — flip the row to in_progress in task-status.json and stamp',
  '# .pipeline/current-task with the id. Extraction is bounded to the H9 id',
  '# grammar so trailing prose after the id never matches.',
  'if [[ "$LINE1" =~ ^Task:\\ ([A-Za-z0-9._-]+|none)$ ]]; then',
  '  TASK_ID="${BASH_REMATCH[1]}"',
  '  if [ "$TASK_ID" != "none" ]; then',
  '    node -e \'',
  'const { readFileSync, writeFileSync, mkdirSync, renameSync, rmSync } = require("fs");',
  'const { join } = require("path");',
  'const id = process.argv[1];',
  'const pipelineDir = join(process.cwd(), ".pipeline");',
  'const statusPath = join(pipelineDir, "task-status.json");',
  'const currentTaskPath = join(pipelineDir, "current-task");',
  '',
  'const abstain = (reason) => {',
  '  let removalFailed = false;',
  '  let removalError = "";',
  '  try { rmSync(currentTaskPath, { force: true }); } catch (e) {',
  '    if (e && e.code && e.code !== "ENOENT") {',
  '      removalFailed = true;',
  '      removalError = String(e && e.message);',
  '    }',
  '  }',
  '  if (removalFailed) {',
  '    process.stderr.write(',
  '      `pre-dispatch-hook: abstain — ${reason}, and stamp removal also failed: ${removalError} (dispatch Task: ${id})\\n`',
  '    );',
  '  } else {',
  '    process.stderr.write(',
  '      `pre-dispatch-hook: abstain — ${reason} (dispatch Task: ${id})\\n`',
  '    );',
  '  }',
  '  process.exit(0);',
  '};',
  '',
  'let raw;',
  'try {',
  '  raw = readFileSync(statusPath, "utf-8");',
  '} catch (err) {',
  '  abstain("task-status.json unreadable");',
  '}',
  'let parsed;',
  'try {',
  '  parsed = JSON.parse(raw);',
  '} catch (err) {',
  '  abstain("task-status.json unparseable");',
  '}',
  'if (!parsed || typeof parsed !== "object" || !Array.isArray(parsed.tasks)) {',
  '  abstain("task-status.json wrong-shaped");',
  '}',
  'const row = parsed.tasks.find((t) => t && t.id === id);',
  'if (!row) {',
  '  const validIds = parsed.tasks.map((t) => t && t.id).filter((v) => v !== undefined);',
  '  process.stderr.write(',
  '    `PRE dispatch hook: unknown task id "${id}" — not found in task-status.json.\\n` +',
  '    `Valid ids: ${validIds.join(", ")}\\n`,',
  '  );',
  '  process.exit(2);',
  '}',
  'let stampedId;',
  'try {',
  '  stampedId = readFileSync(currentTaskPath, "utf-8");',
  '} catch (err) {',
  '  stampedId = undefined;',
  '}',
  '',
  '// Idempotent re-dispatch: same id as the existing stamp — no-op.',
  'if (stampedId === id) {',
  '  process.exit(0);',
  '}',
  '',
  'row.status = "in_progress";',
  'mkdirSync(pipelineDir, { recursive: true });',
  'const tempFile = join(pipelineDir, `.task-status.${process.pid}.${Math.random().toString(36).slice(2)}.tmp`);',
  'try {',
  '  writeFileSync(tempFile, JSON.stringify(parsed, null, 2));',
  '  renameSync(tempFile, statusPath);',
  '} catch (err) {',
  '  try { rmSync(tempFile, { force: true }); } catch (e) {}',
  '  abstain("status file write/rename failed");',
  '}',
  '',
  '// Overlap guard: dispatching a different id while a stamp exists means the',
  '// build switched tasks mid-flight. Remove the stamp entirely rather than',
  '// overwrite it with the new id, so the prepare-commit-msg hook (#452) has',
  '// no unambiguous task id to attribute commits to and abstains.',
  'if (stampedId !== undefined) {',
  '  try { rmSync(currentTaskPath, { force: true }); } catch (err) {}',
  '} else {',
  '  writeFileSync(currentTaskPath, id);',
  '}',
  '\' "$TASK_ID"',
  '    NODE_EXIT_STATUS=$?',
  '    if [ "$NODE_EXIT_STATUS" -eq 2 ]; then',
  '      exit 2',
  '    fi',
  '  fi',
  'fi',
  '',
  'exit 0',
].join('\n');

/**
 * PostToolUse-style dispatch hook (post-dispatch)
 * Invoked after a subagent dispatch completes. Reads the bounded hook
 * payload from stdin, extracts line 1 of `tool_input.prompt` (same grammar
 * as PRE), and removes .pipeline/current-task iff its content exactly
 * matches the parsed id — mirroring runTaskDone (task-cli.ts:175). Never
 * writes `completed` state: that transition belongs to the conductor, not
 * this hook. Fail-open throughout: an absent stamp, a mismatched stamp, or
 * an unparseable/marker-less payload all exit 0, optionally with a stderr
 * diagnostic.
 */
export const POST_DISPATCH_HOOK = [
  '#!/bin/bash',
  'set -e',
  '',
  '# Bound stdin read to 1MiB to avoid hanging or OOMing on a runaway payload',
  '# timeout 3: never hang the session if the host holds hook stdin open —',
  '# a timed-out (empty/partial) payload falls through the fail-open path.',
  'PAYLOAD="$(timeout 3 head -c 1048576 2>/dev/null || true)"',
  '',
  '# Extract line 1 of tool_input.prompt via a bounded node JSON parse. A',
  '# malformed/missing prompt yields an empty LINE1, which simply falls',
  '# through to the (currently no-op) tail of the hook.',
  'LINE1="$(printf \'%s\' "$PAYLOAD" | node -e \'',
  'let data = "";',
  'process.stdin.on("data", (chunk) => { data += chunk; });',
  'process.stdin.on("end", () => {',
  '  try {',
  '    const payload = JSON.parse(data);',
  '    const prompt = payload && payload.tool_input && payload.tool_input.prompt;',
  '    if (typeof prompt === "string") {',
  '      process.stdout.write(prompt.split("\\n")[0]);',
  '    }',
  '  } catch (err) {',
  '    // Malformed/unparseable payload — fail open: emit a diagnostic on',
  '    // stderr and nothing on stdout, so the caller falls through to the',
  '    // no-op tail (exit 0) rather than blocking dispatch cleanup.',
  '    process.stderr.write(',
  '      "post-dispatch-hook: unparseable payload, passing through: " + String(err && err.message) + "\\n"',
  '    );',
  '  }',
  '});',
  '\' || true)"',
  '',
  '# Fail-open: an empty LINE1 means the payload was unparseable or had no',
  '# tool_input.prompt at all (no signal to validate) — pass through quietly.',
  'if [ -z "$LINE1" ]; then',
  '  exit 0',
  'fi',
  '',
  '# Grammar: line 1 MUST be exactly "Task: <id>" or "Task: none" to be',
  '# actionable. Anything else has no signal to act on — pass through.',
  'if ! [[ "$LINE1" =~ ^Task:\\ ([A-Za-z0-9._-]+|none)$ ]]; then',
  '  exit 0',
  'fi',
  '',
  'TASK_ID="${BASH_REMATCH[1]}"',
  '',
  '# Task: none — nothing to remove.',
  'if [ "$TASK_ID" = "none" ]; then',
  '  exit 0',
  'fi',
  '',
  '# Remove .pipeline/current-task iff its content exactly matches TASK_ID.',
  '# This mirrors runTaskDone (task-cli.ts:175): an absent stamp is',
  '# idempotent success; a mismatched stamp is left untouched with a',
  '# stderr diagnostic. Never write `completed` state — that transition',
  '# belongs to the conductor, not this hook.',
  'node -e \'',
  'const { readFileSync, rmSync } = require("fs");',
  'const { join } = require("path");',
  'const id = process.argv[1];',
  'const pipelineDir = join(process.cwd(), ".pipeline");',
  'const currentTaskPath = join(pipelineDir, "current-task");',
  'let stampContent;',
  'try {',
  '  stampContent = readFileSync(currentTaskPath, "utf-8");',
  '} catch (err) {',
  '  // Stamp file does not exist — idempotent success, nothing to do.',
  '  process.exit(0);',
  '}',
  'if (stampContent !== id) {',
  '  process.stderr.write(',
  '    `post-dispatch-hook: task id mismatch: requested "${id}" but stamp contains "${stampContent}" — leaving stamp untouched.\\n`,',
  '  );',
  '  process.exit(0);',
  '}',
  'try {',
  '  rmSync(currentTaskPath, { force: true });',
  '} catch (err) {',
  '  process.stderr.write(',
  '    "post-dispatch-hook: failed to remove stamp file: " + String(err && err.message) + "\\n"',
  '  );',
  '}',
  '\' "$TASK_ID"',
  '',
  'exit 0',
].join('\n');

/**
 * PreToolUse mutation gate (Surface B of #505 inline build-work attribution
 * enforcement). Wired with matcher `Edit|Write|NotebookEdit|Bash`. Blocks
 * unstamped mutation attempts while a build step is active, AND (independent of
 * stamp) any attempt to mutate the engine-owned `.pipeline` machinery.
 *
 * NOTE ON LAYERING (#627, docs-verified): daemon build sessions run with
 * `--dangerously-skip-permissions` (step-runners.ts / claude-provider.ts).
 * Per current Claude Code docs (permission-modes.md, semantics documented for
 * v2.1.200+), permissions.deny rules AND PreToolUse hooks both still apply in
 * that mode — so worktree-prepare wires ENGINE_OWNED_DENY_RULES (below) as a
 * declarative second layer. This hook remains the PRIMARY control because
 * deny rules only match declared tool inputs (file_path); they cannot see
 * into a Bash heredoc/tee/interpreter inline write, which is exactly the
 * bypass observed live.
 *
 * - `.pipeline/build-step-active` marker ABSENT → enforcement inactive,
 *   pass through (exit 0) regardless of tool or stamp.
 * - Marker present + `.pipeline/current-task` absent/empty + tool is
 *   Edit/Write/NotebookEdit → exit 2 with the ADR redirect message.
 * - Marker present + stamp present → pass through (exit 0); the mutation is
 *   happening inside a stamped Agent dispatch — UNLESS it targets an
 *   engine-owned path (below).
 * - Engine-owned `.pipeline` paths (`current-task`, `build-step-active`,
 *   `task-evidence`, `attribution-verdict`) are written ONLY by the engine.
 *   Any agent write to them — via Edit/Write/NotebookEdit OR via Bash
 *   (redirect/heredoc/tee/rm/sed -i, or an interpreter inline write such as
 *   `python3 -c "open(...,'w')"` that hides the path inside quotes) — is
 *   refused exit-2 REGARDLESS of stamp (#627: closes the Bash bypass and the
 *   "agent forges its own stamp" bypass). The set is deliberately tight:
 *   `task-status.json` and `HALT`, which skills legitimately write, are NOT
 *   protected here (precision over breadth — do not break normal workflows).
 * - Bash + unstamped: a `git commit` invocation scan blocks unstamped commit
 *   attempts (precedent: hooks/claude/block-destructive-git.sh quote-span
 *   scanning).
 * - Unparseable payload → fail-open (exit 0), matching the #494 degradation
 *   rule and the PRE/POST dispatch hooks' behavior above.
 */
/**
 * Engine-owned `.pipeline` machinery files — written ONLY by the engine, never
 * by agent sessions (#433 current-task attribution, #302 engine-owned status,
 * #627 bypass hardening). Single source of truth for BOTH enforcement layers:
 * the mutation-gate hook's ENGINE_OWNED_RE and the declarative
 * permissions.deny rules wired by worktree-prepare. Deliberately tight:
 * task-status.json and HALT, which skills legitimately write, are excluded.
 */
export const ENGINE_OWNED_PIPELINE_FILES = [
  'current-task',
  'build-step-active',
  'task-evidence',
  'attribution-verdict',
] as const;

/**
 * Declarative permissions.deny rules for the engine-owned set (#627
 * defense-in-depth). Docs-verified (permission-modes.md, semantics documented
 * for v2.1.200+): deny rules apply in EVERY mode, including
 * bypassPermissions / --dangerously-skip-permissions — so this layer IS live
 * in daemon builds. The PreToolUse mutation-gate hook remains the PRIMARY
 * control: deny rules match declared tool inputs (file_path), so they cannot
 * see into a Bash heredoc/tee/interpreter inline write; the hook covers that
 * surface. task-evidence/attribution-verdict get a trailing `*` because
 * variants exist on disk (e.g. task-evidence.json); current-task and
 * build-step-active are exact so a sibling name is not over-blocked.
 */
export const ENGINE_OWNED_DENY_RULES: string[] = (
  ['Edit', 'Write', 'NotebookEdit'] as const
).flatMap((tool) => [
  `${tool}(.pipeline/current-task)`,
  `${tool}(.pipeline/build-step-active)`,
  `${tool}(.pipeline/task-evidence*)`,
  `${tool}(.pipeline/attribution-verdict*)`,
]);

export const MUTATION_GATE_HOOK = [
  '#!/bin/bash',
  'set -e',
  '',
  '# Surface flag from settings wiring: "write" (Edit|Write|NotebookEdit',
  '# matcher) or "bash" (Bash matcher). Lets the write surface fail CLOSED',
  '# without depending on payload delivery at all.',
  'SURFACE="${1:-}"',
  '',
  'MARKER_PATH=".pipeline/build-step-active"',
  'STAMP_PATH=".pipeline/current-task"',
  '',
  '# Enforcement inactive (no build step in flight, or cutover not reached) —',
  '# pass through without even looking at the payload.',
  'if [ ! -f "$MARKER_PATH" ]; then',
  '  exit 0',
  'fi',
  '',
  'STAMP=""',
  'if [ -f "$STAMP_PATH" ]; then',
  '  STAMP="$(tr -d "[:space:]" < "$STAMP_PATH")"',
  'fi',
  '',
  'REDIRECT_MSG="implementation happens inside a stamped Agent dispatch — dispatch with \\"Task: <id>\\" line 1, or use \\"Task: none\\" for non-implementation work"',
  'ENGINE_MSG="refused: .pipeline/{current-task,build-step-active,task-evidence,attribution-verdict} are engine-owned attribution/gate state (#433/#302) — agent sessions must never write them; only the engine manages these files"',
  '',
  '# Engine-owned .pipeline machinery — written ONLY by the engine. Kept tight',
  '# on purpose: task-status.json and HALT (which skills legitimately write) are',
  '# NOT included, so normal build/TDD workflows are not over-blocked. The',
  '# trailing class rejects a match on a longer sibling name (e.g. current-task2).',
  "ENGINE_OWNED_RE='[.]pipeline/(current-task|build-step-active|task-evidence|attribution-verdict)([^A-Za-z0-9_-]|$)'",
  '',
  '# Write surface fail-CLOSED short-circuit: a missing stamp blocks WITHOUT',
  '# needing the payload — the matcher already proves this is a file mutation,',
  '# so we still refuse even if the host never delivers hook stdin. (A stamped',
  '# write falls through to the payload parse below, where an engine-owned',
  '# file_path is still refused.)',
  'if [ "$SURFACE" = "write" ] && [ -z "$STAMP" ]; then',
  '  echo "$REDIRECT_MSG" >&2',
  '  exit 2',
  'fi',
  '',
  '# Bound stdin read to 1MiB to avoid hanging or OOMing on a runaway payload.',
  '# timeout 3: never hang the session if the host holds hook stdin open — a',
  '# timed-out (empty/partial) payload falls through the fail-open path. For a',
  '# stamped write with an undelivered payload we cannot see file_path, so we',
  '# pass (the Bash arm and git hook still guard the engine-owned set).',
  'PAYLOAD="$(timeout 3 head -c 1048576 2>/dev/null || true)"',
  '',
  '# Extract tool_name, tool_input.command (Bash), and tool_input.file_path /',
  '# notebook_path (write tools) via a bounded node JSON parse, tab-joined so',
  '# bash can split in one read. Tabs/newlines in fields are flattened to spaces',
  '# so the tab join stays unambiguous. An unparseable payload yields empty',
  '# PARSED, which falls through to the fail-open branch below.',
  'PARSED="$(printf \'%s\' "$PAYLOAD" | node -e \'',
  'let data = "";',
  'process.stdin.on("data", (chunk) => { data += chunk; });',
  'process.stdin.on("end", () => {',
  '  try {',
  '    const payload = JSON.parse(data);',
  '    const toolName = typeof payload.tool_name === "string" ? payload.tool_name : "";',
  '    const ti = payload && payload.tool_input ? payload.tool_input : {};',
  '    const command = typeof ti.command === "string" ? ti.command : "";',
  '    const filePath = typeof ti.file_path === "string" ? ti.file_path : (typeof ti.notebook_path === "string" ? ti.notebook_path : "");',
  '    const clean = (s) => s.replace(/[\\t\\n]/g, " ");',
  '    process.stdout.write(toolName + "\\t" + clean(command) + "\\t" + clean(filePath));',
  '  } catch (err) {',
  '    // Malformed/unparseable payload — fail open: emit a diagnostic on',
  '    // stderr and nothing on stdout, so the caller falls through to the',
  '    // fail-open branch (exit 0) rather than blocking the mutation.',
  '    process.stderr.write(',
  '      "mutation-gate-hook: unparseable payload, passing through: " + String(err && err.message) + "\\n"',
  '    );',
  '  }',
  '});',
  '\' || true)"',
  '',
  '# Fail-open: an empty PARSED means the payload was unparseable — no signal',
  '# to gate on, so pass through quietly rather than blocking the mutation.',
  'if [ -z "$PARSED" ]; then',
  '  exit 0',
  'fi',
  '',
  '# Split the three tab-delimited fields (exactly two tabs from the parser).',
  'TOOL_NAME="${PARSED%%$\'\\t\'*}"',
  'REST="${PARSED#*$\'\\t\'}"',
  'COMMAND="${REST%%$\'\\t\'*}"',
  'FILE_PATH="${REST##*$\'\\t\'}"',
  '',
  'case "$TOOL_NAME" in',
  '  Edit|Write|NotebookEdit)',
  '    # Engine-owned target is refused even inside a stamped dispatch — the',
  '    # engine owns these files, not the agent.',
  '    if [ -n "$FILE_PATH" ] && printf \'%s\' "$FILE_PATH" | grep -qE "$ENGINE_OWNED_RE"; then',
  '      echo "$ENGINE_MSG" >&2',
  '      exit 2',
  '    fi',
  '    if [ -z "$STAMP" ]; then',
  '      echo "$REDIRECT_MSG" >&2',
  '      exit 2',
  '    fi',
  '    exit 0',
  '    ;;',
  '  Bash)',
  '    # (1) Engine-owned path WRITE — refused regardless of stamp. This closes',
  '    # the heredoc/tee/redirect/python-c bypass around the Edit|Write block.',
  '    # Detection A (mention-safe): strip quoted spans so a path named inside a',
  '    # commit message / echo is not a false positive, then look for a',
  '    # redirection or a file-mutating command targeting the engine-owned set.',
  '    SCAN=$(printf \'%s\' "$COMMAND" | sed -E "s/\'[^\']*\'//g; s/\\"[^\\"]*\\"//g")',
  '    if printf \'%s\' "$SCAN" | grep -qE "(>>?|>\\|)[[:space:]]*$ENGINE_OWNED_RE"; then',
  '      echo "$ENGINE_MSG" >&2',
  '      exit 2',
  '    fi',
  '    if printf \'%s\' "$SCAN" | grep -qE "(^|[;&|([:space:]])(tee|rm|mv|cp|truncate|dd|install|ln|sed)[[:space:]].*$ENGINE_OWNED_RE"; then',
  '      echo "$ENGINE_MSG" >&2',
  '      exit 2',
  '    fi',
  '    # Detection B: an interpreter inline script (python3 -c, node -e, perl -e,',
  '    # ruby -e, php -r) hides the path inside quotes, so Detection A\\047s',
  '    # quote-strip would drop it — scan the RAW command instead. An interpreter',
  '    # -c/-e/-r invocation referencing an engine-owned path is refused (reading',
  '    # these machinery files this way is not a supported workflow either).',
  '    if printf \'%s\' "$COMMAND" | grep -qE "(python3?|perl|ruby|node|php)[[:space:]]+-[cer][[:space:]]" && printf \'%s\' "$COMMAND" | grep -qE "$ENGINE_OWNED_RE"; then',
  '      echo "$ENGINE_MSG" >&2',
  '      exit 2',
  '    fi',
  '    # (2) Unstamped `git commit` — blocked at invocation position only.',
  '    if [ -z "$STAMP" ]; then',
  '      # Split on command separators (&&, ||, ;, |, () so each resulting line',
  '      # represents a distinct invocation position. Anchoring the match at',
  '      # line-start means `git commit` is only detected when it is the invoked',
  '      # command itself — a substring later in an argument does not false-block.',
  '      SCAN_LINES=$(printf \'%s\' "$SCAN" | sed -E "s/(&&|\\|\\||[;|]|\\()/\\n/g")',
  '      if echo "$SCAN_LINES" | grep -qE \'^[[:space:]]*git[[:space:]]+commit\\b\'; then',
  '        echo "$REDIRECT_MSG" >&2',
  '        exit 2',
  '      fi',
  '    fi',
  '    exit 0',
  '    ;;',
  '  *)',
  '    exit 0',
  '    ;;',
  'esac',
].join('\n');
