/**
 * Session-lifecycle hook scripts embedded as engine assets
 *
 * Hooks are written to .pipeline/session-hooks/ at worktree provisioning
 * and wired via settings.json hook entries. They use only bash and POSIX
 * tools — no dist references, no conduct-ts invocations. stdin is bounded
 * via `head -c` so a runaway payload can never hang or OOM the hook.
 */

/**
 * PreToolUse-style dispatch hook (pre-dispatch)
 * Invoked before a subagent is dispatched. Reads the bounded hook payload
 * from stdin, extracts line 1 of `tool_input.prompt`, and passes through
 * (exit 0, no state touched) when it is exactly "Task: none". Further
 * behavior for real task ids is added in later tasks.
 */
export const PRE_DISPATCH_HOOK = [
  '#!/bin/bash',
  'set -e',
  '',
  '# Bound stdin read to 1MiB to avoid hanging or OOMing on a runaway payload',
  '# timeout 3: never hang the session if the host holds hook stdin open —',
  '# a timed-out (empty/partial) payload falls through the fail-open path.',
  'PAYLOAD="$(timeout 3 head -c 1048576 2>/dev/null || true)"',
  '',
  '# Extract line 1 of tool_input.prompt via a bounded node JSON parse. A',
  '# malformed/missing prompt yields an empty LINE1, which simply falls',
  '# through to the (currently no-op) tail of the hook.',
  'LINE1="$(printf \'%s\' "$PAYLOAD" | node -e \'',
  'let data = "";',
  'process.stdin.on("data", (chunk) => { data += chunk; });',
  'process.stdin.on("end", () => {',
  '  try {',
  '    const payload = JSON.parse(data);',
  '    const prompt = payload && payload.tool_input && payload.tool_input.prompt;',
  '    if (typeof prompt === "string") {',
  '      process.stdout.write(prompt.split("\\n")[0]);',
  '    }',
  '  } catch (err) {',
  '    // Malformed/unparseable payload — fail open: emit a diagnostic on',
  '    // stderr and nothing on stdout, so the caller falls through to the',
  '    // no-op tail (exit 0) rather than blocking the dispatch.',
  '    require("fs").writeSync(2,',
  '      "pre-dispatch-hook: unparseable payload, passing through: " + String(err && err.message) + "\\n"',
  '    );',
  '  }',
  '});',
  '\' || true)"',
  '',
  '# Fail-open: an empty LINE1 means the payload was unparseable or had no',
  '# tool_input.prompt at all (no signal to validate) — pass through quietly',
  '# rather than treating "nothing to say" as a grammar violation.',
  'if [ -z "$LINE1" ]; then',
  '  exit 0',
  'fi',
  '',
  '# Attribution is telemetry only. A non-marker prompt produces no row update',
  '# and must never block the dispatch.',
  'if ! [[ "$LINE1" =~ ^Task:\\ ([A-Za-z0-9._-]+|none)$ ]]; then',
  '  exit 0',
  'fi',
  '',
  '# Record a dispatch-count sentinel: every grammar-valid "Task: <id>" or',
  '# "Task: none" dispatch appends one line to .pipeline/dispatch-count,',
  '# regardless of subsequent branch outcome. Used by later zero-work',
  '# detection (Task 15) to tell whether any dispatch happened at all.',
  '# Idempotent/best-effort: created if absent, appended to otherwise; a',
  '# failure here (e.g. read-only fs) must never block the dispatch.',
  'mkdir -p .pipeline 2>/dev/null || true',
  'printf \'%s\\n\' "$LINE1" | tee -a .pipeline/dispatch-count >/dev/null 2>&1 || true',
  '',
  '# Task: none — pass through without touching any pipeline state.',
  'if [ "$LINE1" = "Task: none" ]; then',
  '  exit 0',
  'fi',
  '',
  '# Task: <id> — flip only its own row to in_progress in task-status.json.',
  '# Extraction is bounded to the H9 id',
  '# grammar so trailing prose after the id never matches.',
  'if [[ "$LINE1" =~ ^Task:\\ ([A-Za-z0-9._-]+|none)$ ]]; then',
  '  TASK_ID="${BASH_REMATCH[1]}"',
  '  if [ "$TASK_ID" != "none" ]; then',
  '    node -e \'',
  'const { readFileSync, writeFileSync, mkdirSync, renameSync, rmSync, writeSync } = require("fs");',
  'const { join } = require("path");',
  'const id = process.argv[1];',
  'const pipelineDir = join(process.cwd(), ".pipeline");',
  'const statusPath = join(pipelineDir, "task-status.json");',
  'const lockPath = join(pipelineDir, ".task-status.lock");',
  '',
  'const abstain = (reason) => {',
  '  writeSync(2, `pre-dispatch-hook: abstain — ${reason} (dispatch Task: ${id})\\n`);',
  '  process.exit(0);',
  '};',
  '',
  'let locked = false;',
  'for (let attempt = 0; attempt < 100; attempt += 1) {',
  '  try { mkdirSync(lockPath); locked = true; break; } catch {}',
  '  Atomics.wait(new Int32Array(new SharedArrayBuffer(4)), 0, 0, 10);',
  '}',
  'if (!locked) abstain("task-status telemetry lock unavailable");',
  'try {',
  'let raw;',
  'try {',
  '  raw = readFileSync(statusPath, "utf-8");',
  '} catch (err) {',
  '  abstain("task-status.json unreadable");',
  '}',
  'let parsed;',
  'try {',
  '  parsed = JSON.parse(raw);',
  '} catch (err) {',
  '  abstain("task-status.json unparseable");',
  '}',
  'if (!parsed || typeof parsed !== "object" || !Array.isArray(parsed.tasks)) {',
  '  abstain("task-status.json wrong-shaped");',
  '}',
  'const row = parsed.tasks.find((t) => t && t.id === id);',
  'if (!row) {',
  '  abstain(`unknown task id "${id}"`);',
  '}',
  'row.status = "in_progress";',
  'mkdirSync(pipelineDir, { recursive: true });',
  'const tempFile = join(pipelineDir, `.task-status.${process.pid}.${Math.random().toString(36).slice(2)}.tmp`);',
  'try {',
  '  writeFileSync(tempFile, JSON.stringify(parsed, null, 2));',
  '  renameSync(tempFile, statusPath);',
  '} catch (err) {',
  '  try { rmSync(tempFile, { force: true }); } catch (e) {}',
  '  abstain("status file write/rename failed");',
  '}',
  '} finally {',
  '  try { rmSync(lockPath, { recursive: true, force: true }); } catch {}',
  '}',
  '\' "$TASK_ID"',
  '  fi',
  'fi',
  '',
  'exit 0',
].join('\n');

/**
 * PreToolUse phase-scoped .docs write-guard (#788). Wired with matcher
 * `Edit|Write|NotebookEdit`. Blocks mutation of spec/plan artifacts under
 * `.docs/` while a build phase is active, unless the phase marker's
 * allowlist explicitly permits the target path.
 *
 * - `.pipeline/phase-active` marker ABSENT → enforcement inactive, exit 0
 *   WITHOUT reading stdin at all (must never block waiting on payload
 *   delivery when inert).
 * - Marker present + target path outside `.docs/` → exit 0 (Task 5 scope).
 * - Marker present + target under `.docs/` → block/allow logic added in
 *   Tasks 6-8; this task lands only the inert fast paths above.
 * - Unparseable payload → fail-open when the phase is inactive; active-phase
 *   undeterminable writes fail closed.
 */
export const DOCS_GUARD_HOOK = [
  '#!/bin/bash',
  'set -e',
  '',
  'MARKER_PATH=".pipeline/phase-active"',
  '',
  '# Enforcement inactive (no build phase in flight) — pass through WITHOUT',
  '# reading stdin, so this never blocks waiting on payload delivery.',
  'if [ ! -f "$MARKER_PATH" ]; then',
  '  exit 0',
  'fi',
  '',
  '# Bound stdin read to 1MiB to avoid hanging or OOMing on a runaway payload.',
  '# timeout 3: never hang the session if the host holds hook stdin open —',
  '# a timed-out (empty/partial) payload falls through the fail-open path.',
  'PAYLOAD="$(timeout 3 head -c 1048576 2>/dev/null || true)"',
  '',
  '# Extract the target path (Edit/Write use tool_input.file_path,',
  '# NotebookEdit uses tool_input.notebook_path) via a bounded node JSON',
  '# parse. A malformed/unparseable payload yields an empty PARSED, which',
  '# falls through to the fail-open branch below.',
  'TARGET="$(printf \'%s\' "$PAYLOAD" | node -e \'',
  'let data = "";',
  'process.stdin.on("data", (chunk) => { data += chunk; });',
  'process.stdin.on("end", () => {',
  '  try {',
  '    const payload = JSON.parse(data);',
  '    const input = payload && payload.tool_input ? payload.tool_input : {};',
  '    const target =',
  '      typeof input.file_path === "string"',
  '        ? input.file_path',
  '        : typeof input.notebook_path === "string"',
  '          ? input.notebook_path',
  '          : "";',
  '    process.stdout.write(target);',
  '  } catch (err) {',
  '    // Malformed/unparseable payload — fail open: emit a diagnostic on',
  '    // stderr and nothing on stdout, so the caller falls through to the',
  '    // fail-open branch (exit 0) rather than blocking the mutation.',
  '    process.stderr.write(',
  '      "docs-guard-hook: unparseable payload, passing through: " + String(err && err.message) + "\\n"',
  '    );',
  '  }',
  '});',
  '\' || true)"',
  '',
  '# Fail-closed: by this point the phase-active marker is known to exist',
  '# (the marker-absent fast path already exited above), so an empty TARGET',
  '# — payload unparseable, timed out, or carrying no path — is undeterminable',
  '# under an active phase. This write-surface hook must not pass an',
  '# undeterminable target through silently: block it.',
  'if [ -z "$TARGET" ]; then',
  '  {',
  '    echo "docs-guard: blocked write — target path could not be determined while a build phase is active."',
  '    echo "Marker: .pipeline/phase-active"',
  '    echo "Remedy: if this write is intentional and allowlisted, no action needed; otherwise run \'rm .pipeline/phase-active\' only if you are certain the phase should not be active."',
  '  } >&2',
  '  exit 2',
  'fi',
  '',
  '# Normalize an absolute TARGET (as delivered by the real Claude Code host,',
  '# e.g. "$PWD/.docs/plans/x.md") to a repo-root-relative path so the',
  '# case-glob match below works for both absolute and relative inputs. The',
  '# hook always runs with cwd set to the project root, so stripping a literal',
  '# "$PWD/" prefix is sufficient;',
  '# relative-path callers (e.g. unit tests) are left untouched.',
  'case "$TARGET" in',
  '  "$PWD"/*)',
  '    TARGET="${TARGET#"$PWD"/}"',
  '    ;;',
  'esac',
  '',
  'case "$TARGET" in',
  '  .docs/*|.docs)',
  '    # Allow-prefix bypass: any `allow: <prefix>` line in the marker exempts',
  '    # targets that start with that literal prefix string. Prefixes are',
  '    # written with a trailing slash (see writePhaseMarker), so a plain',
  '    # `case`-glob prefix match is already directory-segment-boundary-safe:',
  '    # \'.docs/retros-evil/x.md\' does not start with the literal string',
  '    # \'.docs/retros/\', so it does not false-match the \'.docs/retros/\' allow.',
  '    while IFS= read -r ALLOW_PREFIX; do',
  '      case "$TARGET" in',
  '        "$ALLOW_PREFIX"*)',
  '          exit 0',
  '          ;;',
  '      esac',
  '    done < <(sed -n \'s/^allow: //p\' "$MARKER_PATH")',
  '    # Default-deny: no allow-prefix matched — block the write.',
  '    STEP="$(sed -n \'s/^step: //p\' "$MARKER_PATH" | head -n1)"',
  '    PHASE="$(sed -n \'s/^phase: //p\' "$MARKER_PATH" | head -n1)"',
  '    STEP="${STEP:-unknown}"',
  '    PHASE="${PHASE:-unknown}"',
  '    {',
  '      echo "docs-guard: blocked write to \'$TARGET\' during $PHASE phase (step: $STEP) - spec artifacts are frozen during BUILD/SHIP."',
  '      echo "Marker: .pipeline/phase-active"',
  '      echo "Remedy: if this write is intentional and allowlisted, no action needed; otherwise run \'rm .pipeline/phase-active\' only if you are certain the phase should not be active."',
  '    } >&2',
  '    exit 2',
  '    ;;',
  '  *)',
  '    exit 0',
  '    ;;',
  'esac',
].join('\n');
